// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/6/2024, 0:00:57
const configMerger = require("C:/Users/dchav/Desktop/LA PUTA MIERDA/CLON FILMIN_API _cgpt/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/dchav/Desktop/LA PUTA MIERDA/CLON FILMIN_API _cgpt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dchav/Desktop/LA PUTA MIERDA/CLON FILMIN_API _cgpt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dchav/Desktop/LA PUTA MIERDA/CLON FILMIN_API _cgpt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dchav/Desktop/LA PUTA MIERDA/CLON FILMIN_API _cgpt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dchav/Desktop/LA PUTA MIERDA/CLON FILMIN_API _cgpt/plugins/**/*.{js,ts,mjs}","C:/Users/dchav/Desktop/LA PUTA MIERDA/CLON FILMIN_API _cgpt/composables/**/*.{js,ts,mjs}","C:/Users/dchav/Desktop/LA PUTA MIERDA/CLON FILMIN_API _cgpt/utils/**/*.{js,ts,mjs}","C:/Users/dchav/Desktop/LA PUTA MIERDA/CLON FILMIN_API _cgpt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dchav/Desktop/LA PUTA MIERDA/CLON FILMIN_API _cgpt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/dchav/Desktop/LA PUTA MIERDA/CLON FILMIN_API _cgpt/app.config.{js,ts,mjs}"] }));

module.exports = config
